[trifinger_rl_experiment]
task = "lift"  # "push" or "lift"

record_transitions = true
haptic_type = "raw"

# Specify a policy
lift_policy = "trifinger_rl_example.example.NoHapticsPolicy"
push_policy = "trifinger_rl_example.example.TorchPushPolicy"
